### PR TITLE
Update database automatically when releasing

### PR DESCRIPTION
**Pull request by zhuhaow**
Remove the database shipped with the library, instead, the database will be downloaded automatically if it doesn't exist. When the configuration is Release, it will also update the database so the final product always has the up to date database.

### CODE REVIEW

**Comment by lexrus** [comment]
Fabulous!
Thanks.

**Comment by zhuhaow** [comment]
Can you release a new version now?

**Comment by zhuhaow** [comment]
Thanks

**Comment by zhuhaow** [comment]
Is the database downloaded from `http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz`?

Why is it not working?

**Comment by zhuhaow** [comment]
I made a mistake, fixing

**Comment by lexrus** [comment]
Failed to pass pod lint. FYI.

**Comment by zhuhaow** [comment]
It doesn't seem like cocoapod will allow some setting script run before init?

**Comment by zhuhaow** [comment]
Found `prepare_command`

**Pull request merged**
